### PR TITLE
backend to main

### PR DESCRIPTION
**Pull request by aaspinwall**

### CODE REVIEW

**Comment by aaspinwall** [comment]
It works! Vercel hates it but we can deal with that later.

**Comment by aaspinwall** [comment]
Integrates #80 and resolves conflicts
@andrewbaldwin44 @kolbymckeown please check that your refactoring is there as you intended. There were two files that didn't have properly resolving paths. I commented them out for now. 

backend > tests > graphqlTestCall.js
backend > schema > schema.root.js

**Comment by ShaiGilboa** [comment]
I'm closing this one, as I'm going to create a new one with this implemented in it :)

**Comment by andrewbaldwin44** [comment]
@ShaiGilboa Kolby's discussing it with Alejandro. There's a little git trick we can do by making the main and backend branches identical and then just force pushing

**Comment by kolbymckeown** [comment]
If @ShaiGilboa thinks he can get through it then power to him @andrewbaldwin44 - better to have it ready for the walkthrough tomorrow anyways

**Pull request closed without merging**
